apiVersion: batch/v1
kind: Job
metadata:
  generateName: test-message-
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  template:
    spec:
      containers:
      - name: test-message
        image: ubuntu
        command: |
          #!/bin/bash
          apt update && apt upgrade -y
      restartPolicy: Never
  backoffLimit: 2