apiVersion: batch/v1
kind: Job
metadata:
  generateName: test-message-
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  template:
    spec:
      containers:
      - name: test-message
        image: 320996968493.dkr.ecr.eu-west-1.amazonaws.com/test-accounts
        imagePullPolicy: Always
        env:
          - name: ENV
            value: "{{ .Values.environment }}"
          - name: SCIM_AUTHORIZATION
            value: "{{ .Values.scimAuth }}"
          - name: USER_PASSWORD
            value: "{{ .Values.userPassword }}"
      restartPolicy: Never
      imagePullSecrets:
        - name: aws-registry
  backoffLimit: 2